spring:
  application:
    name: TelegramReminderBot
  datasource:
    url: jdbc:postgresql://localhost:5432/vano_bot
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      # ddl-auto: create  чтобы база создавалась при запуске (none-не создавалась)
      ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          show_sql: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true